# Gotting knowledge about the data

The data file contains the approximate number of immigrants from all countries who went to Canada from 1980 to 2013. Furthermore, it includes additional information about the location of each country, illustrating the continent in which it is located and whether the region is developing or already developed.

In [2]:
# Reading the data:
import pandas as pd
import matplotlib as mpl

In [11]:
original_dataframe = pd.read_csv('../data/imigrantes_canada.csv')

In [5]:
# Visualizating the dataset
original_dataframe

,País,Continente,Região,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afeganistão,Ásia,Sul da Ásia,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albânia,Europa,Sul da Europa,1,0,0,0,0,0,1,...,1223,856,702,560,716,561,539,620,603,15699
2,Argélia,África,Norte da África,80,67,71,69,63,44,69,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,Samoa Americana,Oceânia,Polinésia,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europa,Sul da Europa,0,0,0,0,0,0,2,...,0,1,1,0,0,0,0,1,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Vietnã,Ásia,Sudeste Asiático,1191,1829,2162,3404,7583,5907,2741,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146
191,Saara Ocidental,África,Norte da África,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,2
192,Iémen,Ásia,Ásia Ocidental,1,2,1,6,0,18,7,...,161,140,122,133,128,211,160,174,217,2985
193,Zâmbia,África,África Oriental,11,17,11,7,16,9,15,...,91,77,71,64,60,102,69,46,59,1677
194,Zimbábue,África,África Oriental,72,114,102,44,32,29,43,...,615,454,663,611,508,494,434,437,407,8598

In [6]:
# The infos about the dataset:
original_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 38 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   País        195 non-null    str
 1   Continente  195 non-null    str
 2   Região      195 non-null    str
 3   1980        195 non-null    int64
 4   1981        195 non-null    int64
 5   1982        195 non-null    int64
 6   1983        195 non-null    int64
 7   1984        195 non-null    int64
 8   1985        195 non-null    int64
 9   1986        195 non-null    int64
 10  1987        195 non-null    int64
 11  1988        195 non-null    int64
 12  1989        195 non-null    int64
 13  1990        195 non-null    int64
 14  1991        195 non-null    int64
 15  1992        195 non-null    int64
 16  1993        195 non-null    int64
 17  1994        195 non-null    int64
 18  1995        195 non-null    int64
 19  1996        195 non-null    int64
 20  1997        195 non-null    int64
 21  1998        195 non-null    int64
 22  1999        195 non-null    int64
 23  2000        195 non-null    int64
 24  2001        195 non-null    int64
 25  2002        195 non-null    int64
 26  2003        195 non-null    int64
 27  2004        195 non-null    int64
 28  2005        195 non-null    int64
 29  2006        195 non-null    int64
 30  2007        195 non-null    int64
 31  2008        195 non-null    int64
 32  2009        195 non-null    int64
 33  2010        195 non-null    int64
 34  2011        195 non-null    int64
 35  2012        195 non-null    int64
 36  2013        195 non-null    int64
 37  Total       195 non-null    int64
dtypes: int64(35), str(3)
memory usage: 58.0 KB

Since there are no null data points, and we are not preparing a database to train a machine learning model, there is no need to process the dataset.

### Analisar as tendências de imigração do Brasil para o Canadá ao longo dos anos

In [24]:
# Verifying if there is a duplicated rows before to make the countrys be the indexes
original_dataframe.duplicated().sum()

np.int64(0)

In [25]:
dataframe = original_dataframe

In [26]:
dataframe.set_index('País', inplace=True)

In [27]:
dataframe

,Continente,Região,1980,1981,1982,1983,1984,1985,1986,1987,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
País,,,,,,,,,,,,,,,,,,,,,
Afeganistão,Ásia,Sul da Ásia,16,39,39,47,71,340,496,741,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
Albânia,Europa,Sul da Europa,1,0,0,0,0,0,1,2,...,1223,856,702,560,716,561,539,620,603,15699
Argélia,África,Norte da África,80,67,71,69,63,44,69,132,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
Samoa Americana,Oceânia,Polinésia,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,6
Andorra,Europa,Sul da Europa,0,0,0,0,0,0,2,0,...,0,1,1,0,0,0,0,1,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnã,Ásia,Sudeste Asiático,1191,1829,2162,3404,7583,5907,2741,1406,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146
Saara Ocidental,África,Norte da África,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,2
Iémen,Ásia,Ásia Ocidental,1,2,1,6,0,18,7,12,...,161,140,122,133,128,211,160,174,217,2985
Zâmbia,África,África Oriental,11,17,11,7,16,9,15,23,...,91,77,71,64,60,102,69,46,59,1677
Zimbábue,África,África Oriental,72,114,102,44,32,29,43,68,...,615,454,663,611,508,494,434,437,407,8598

In [28]:
# Creating a list with year intervals
years = list(map(str, range(1980, 2014)))

In [29]:
years

['1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013']

In [41]:
my_years = dataframe.columns[2:-1]

my_years

Index(['1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988',
       '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013'],
      dtype='str')

In [42]:
brazil = dataframe.loc['Brasil', my_years]

In [43]:
brazil

1980     211
1981     220
1982     192
1983     139
1984     145
1985     130
1986     205
1987     244
1988     394
1989     650
1990     650
1991     877
1992    1066
1993     866
1994     566
1995     572
1996     586
1997     591
1998     531
1999     626
2000     845
2001     847
2002     745
2003     839
2004     917
2005     969
2006    1181
2007    1746
2008    2138
2009    2509
2010    2598
2011    1508
2012    1642
2013    1714
Name: Brasil, dtype: int64

In [47]:
new_df_brazil_data = {
    'ano': list(brazil.index),
    'amount_of_imigrates': list(brazil.values)
}

brazil_data_dataframe = pd.DataFrame(new_df_brazil_data)

In [49]:
# Imigrants from Brazil to Canada for each year since 1980 to 2013
brazil_data_dataframe

     ano  amount_of_imigrates
0   1980                  211
1   1981                  220
2   1982                  192
3   1983                  139
4   1984                  145
5   1985                  130
6   1986                  205
7   1987                  244
8   1988                  394
9   1989                  650
10  1990                  650
11  1991                  877
12  1992                 1066
13  1993                  866
14  1994                  566
15  1995                  572
16  1996                  586
17  1997                  591
18  1998                  531
19  1999                  626
20  2000                  845
21  2001                  847
22  2002                  745
23  2003                  839
24  2004                  917
25  2005                  969
26  2006                 1181
27  2007                 1746
28  2008                 2138
29  2009                 2509
30  2010                 2598
31  2011                 1508
32  2012                 1642
33  2013                 1714